### ISSUE TITLE
README reopens everytime I close Device Configurator

### ISSUE THREAD

**Issue by zelyanovskyy** [sjcbulldog/mtbassist#11]
1. Create an application.
2. Close README.
3. Open Device Configurator.
4. Close Device Configurator.
5. README reopens switching the focus from the file I've been working on.

Please fix. Thanks!

**Comment by sjcbulldog** [comment]
This was only if you had the display README feature turned on (which it is by default).  The problem was the code that reloaded the ModusToolbox project displayed the readme.  So, after library manager or device configurator was run, which could have changed the ModusToolbox project on disk, the application was reloaded, which in turn displayed the README.  I refectored the reloading so that this would not happen, by noting the difference in a first load and subsequent loads.

**Comment by mykz-cy** [comment]
Thanks! Confirm it is fixed.
