### ISSUE TITLE
Project Creator Target IDE is locked to Eclipse IDE

### ISSUE THREAD

**Issue by cj-follett** [sjcbulldog/mtbassist#2]
When you select Create Project to launch the Project Creator tool, after picking the BSP, the Select Application page shows Eclipse as the Target IDE, and it cannot be changed:
![image](https://user-images.githubusercontent.com/47995211/200015652-3e841a1a-fd94-45e0-b887-247f04672450.png)

This is expected when launching from Eclipse, but not from VS Code.

**Comment by sjcbulldog** [comment]
This is unfortunately a limitation of our ProjectCreator.  I will get this fixed in ModusToolbox 3.1, but I cannot get the behavior I want from the Project Creator in terms of telling an IDE what was created and automatically closing without setting this to Eclipse.  It will be confusing and I wish our development teams had a little more foresight on these kinds of issues.

**Comment by sjcbulldog** [comment]
With the release of ModusToolbox 3.1, this issue is fixed when ModusToolbox 3.1 is found.  The IDE is locked to Microsoft Visual Studio Code.
